# Generated by Django 4.2.2 on 2023-06-14 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='added_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 14, 14, 56, 11, 933743)),
        ),
    ]
