# Generated by Django 4.2.2 on 2023-06-15 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todo_added_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_active',
            new_name='is_completed',
        ),
    ]
